In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\predator\anaconda3\lib\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\predator\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\predator\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\predator\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\predator\anaconda3\lib\site-packages (from mlxtend) (1.5.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\predator\anaconda3\lib\site-packages (from mlxtend) (3.9.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\predator\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\predator\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\predator\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\predator\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\predator\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\predator\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\predator\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\predator\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\predator\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\predator\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\predator\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\predator\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\predator\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [3]:
import numpy as np 
import pandas as pd 
from mlxtend.frequent_patterns import apriori, association_rules

In [15]:
df = pd.read_csv(r"C:\Users\Predator\Downloads\basket_analysis.csv")

In [17]:
df

,Unnamed: 0,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,0,False,True,False,False,True,True,False,True,False,False,False,False,True,False,True,True
1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,2,True,False,True,False,False,True,False,True,False,True,False,False,False,False,True,True
3,3,False,False,True,True,False,True,False,False,False,True,True,True,False,False,False,False
4,4,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,994,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,True
995,995,True,False,False,False,True,False,False,False,True,True,True,False,False,False,True,False
996,996,True,False,False,False,True,True,False,False,False,False,False,False,True,False,False,True
997,997,False,False,True,True,True,False,True,True,True,False,True,False,True,False,True,True
998,998,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True

In [19]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [21]:
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)

In [23]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

In [25]:
print(rules.head())

  antecedents consequents  antecedent support  consequent support   support  \
0     (Apple)     (Bread)            0.383383            0.384384  0.154154
1     (Bread)     (Apple)            0.384384            0.383383  0.154154
2    (Butter)     (Apple)            0.420420            0.383383  0.188188
3     (Apple)    (Butter)            0.383383            0.420420  0.188188
4     (Apple)    (Cheese)            0.383383            0.404404  0.162162

   confidence      lift  representativity  leverage  conviction  \
0    0.402089  1.046059               1.0  0.006788    1.029610
1    0.401042  1.046059               1.0  0.006788    1.029482
2    0.447619  1.167549               1.0  0.027006    1.116289
3    0.490862  1.167549               1.0  0.027006    1.138354
4    0.422977  1.045925               1.0  0.007120    1.032186

   zhangs_metric   jaccard  certainty  kulczynski
0       0.071407  0.251223   0.028759    0.401565
1       0.071524  0.251223   0.028637    0.401565
2       0.247602  0.305691   0.104174    0.469240
3       0.232730  0.305691   0.121538    0.469240
4       0.071208  0.259200   0.031182    0.411983